# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_iSender(object):
    def setupUi(self, iSender):
        iSender.setObjectName("iSender")
        iSender.resize(1096, 528)
        self.centralwidget = QtWidgets.QWidget(iSender)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1101, 591))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.log_widget = QtWidgets.QTableWidget(self.tab)
        self.log_widget.setGeometry(QtCore.QRect(10, 40, 881, 171))
        self.log_widget.setObjectName("log_widget")
        self.log_widget.setColumnCount(5)
        self.log_widget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.log_widget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.log_widget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.log_widget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.log_widget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.log_widget.setHorizontalHeaderItem(4, item)
        self.detail_list = QtWidgets.QListView(self.tab)
        self.detail_list.setGeometry(QtCore.QRect(10, 260, 881, 201))
        self.detail_list.setObjectName("detail_list")
        self.label_51 = QtWidgets.QLabel(self.tab)
        self.label_51.setGeometry(QtCore.QRect(10, 10, 181, 16))
        self.label_51.setObjectName("label_51")
        self.label_69 = QtWidgets.QLabel(self.tab)
        self.label_69.setGeometry(QtCore.QRect(10, 230, 191, 16))
        self.label_69.setObjectName("label_69")
        self.clear_log = QtWidgets.QPushButton(self.tab)
        self.clear_log.setGeometry(QtCore.QRect(640, 0, 93, 28))
        self.clear_log.setObjectName("clear_log")
        self.clear_all_log = QtWidgets.QPushButton(self.tab)
        self.clear_all_log.setGeometry(QtCore.QRect(770, 0, 121, 28))
        self.clear_all_log.setObjectName("clear_all_log")
        self.tabWidget.addTab(self.tab, "")
        self.ip = QtWidgets.QWidget()
        self.ip.setObjectName("ip")
        self.label_3 = QtWidgets.QLabel(self.ip)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 121, 16))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.ip)
        self.label_5.setGeometry(QtCore.QRect(230, 20, 111, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.ip)
        self.label_6.setGeometry(QtCore.QRect(440, 20, 21, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.ip)
        self.label_7.setGeometry(QtCore.QRect(530, 20, 21, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.ip)
        self.label_8.setGeometry(QtCore.QRect(240, 60, 91, 20))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.ip)
        self.label_9.setGeometry(QtCore.QRect(10, 100, 61, 16))
        self.label_9.setObjectName("label_9")
        self.label_11 = QtWidgets.QLabel(self.ip)
        self.label_11.setGeometry(QtCore.QRect(440, 60, 111, 20))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.ip)
        self.label_12.setGeometry(QtCore.QRect(760, 60, 131, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.ip)
        self.label_13.setGeometry(QtCore.QRect(230, 100, 51, 16))
        self.label_13.setObjectName("label_13")
        self.label = QtWidgets.QLabel(self.ip)
        self.label.setGeometry(QtCore.QRect(10, 140, 41, 16))
        self.label.setObjectName("label")
        self.label_57 = QtWidgets.QLabel(self.ip)
        self.label_57.setGeometry(QtCore.QRect(630, 20, 61, 16))
        self.label_57.setObjectName("label_57")
        self.ip_protocol = QtWidgets.QComboBox(self.ip)
        self.ip_protocol.setGeometry(QtCore.QRect(120, 100, 61, 22))
        self.ip_protocol.setObjectName("ip_protocol")
        self.ip_protocol.addItem("")
        self.ip_protocol.addItem("")
        self.ip_protocol.addItem("")
        self.ip_type_of_service = QtWidgets.QLineEdit(self.ip)
        self.ip_type_of_service.setGeometry(QtCore.QRect(130, 20, 71, 21))
        self.ip_type_of_service.setObjectName("ip_type_of_service")
        self.ip_identification = QtWidgets.QLineEdit(self.ip)
        self.ip_identification.setGeometry(QtCore.QRect(350, 20, 71, 20))
        self.ip_identification.setObjectName("ip_identification")
        self.ip_df = QtWidgets.QLineEdit(self.ip)
        self.ip_df.setGeometry(QtCore.QRect(470, 20, 31, 20))
        self.ip_df.setObjectName("ip_df")
        self.ip_mf = QtWidgets.QLineEdit(self.ip)
        self.ip_mf.setGeometry(QtCore.QRect(570, 20, 31, 20))
        self.ip_mf.setObjectName("ip_mf")
        self.ip_offset = QtWidgets.QLineEdit(self.ip)
        self.ip_offset.setGeometry(QtCore.QRect(700, 20, 131, 20))
        self.ip_offset.setObjectName("ip_offset")
        self.ip_time_to_live = QtWidgets.QLineEdit(self.ip)
        self.ip_time_to_live.setGeometry(QtCore.QRect(350, 60, 41, 20))
        self.ip_time_to_live.setObjectName("ip_time_to_live")
        self.ip_source_address = QtWidgets.QLineEdit(self.ip)
        self.ip_source_address.setGeometry(QtCore.QRect(550, 60, 191, 20))
        self.ip_source_address.setObjectName("ip_source_address")
        self.ip_destination_address = QtWidgets.QLineEdit(self.ip)
        self.ip_destination_address.setGeometry(QtCore.QRect(890, 60, 191, 20))
        self.ip_destination_address.setObjectName("ip_destination_address")
        self.ip_option = QtWidgets.QLineEdit(self.ip)
        self.ip_option.setGeometry(QtCore.QRect(300, 100, 781, 20))
        self.ip_option.setObjectName("ip_option")
        self.ip_destination_port = QtWidgets.QLineEdit(self.ip)
        self.ip_destination_port.setGeometry(QtCore.QRect(130, 60, 91, 20))
        self.ip_destination_port.setObjectName("ip_destination_port")
        self.label_2 = QtWidgets.QLabel(self.ip)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 121, 16))
        self.label_2.setObjectName("label_2")
        self.ip_data = QtWidgets.QLineEdit(self.ip)
        self.ip_data.setGeometry(QtCore.QRect(70, 140, 891, 20))
        self.ip_data.setObjectName("ip_data")
        self.ip_log = QtWidgets.QTableWidget(self.ip)
        self.ip_log.setGeometry(QtCore.QRect(10, 220, 521, 211))
        self.ip_log.setObjectName("ip_log")
        self.ip_log.setColumnCount(4)
        self.ip_log.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.ip_log.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_log.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_log.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.ip_log.setHorizontalHeaderItem(3, item)
        self.label_10 = QtWidgets.QLabel(self.ip)
        self.label_10.setGeometry(QtCore.QRect(10, 190, 121, 16))
        self.label_10.setObjectName("label_10")
        self.ip_detail_list = QtWidgets.QListView(self.ip)
        self.ip_detail_list.setGeometry(QtCore.QRect(570, 220, 511, 211))
        self.ip_detail_list.setObjectName("ip_detail_list")
        self.label_39 = QtWidgets.QLabel(self.ip)
        self.label_39.setGeometry(QtCore.QRect(570, 190, 171, 16))
        self.label_39.setObjectName("label_39")
        self.line = QtWidgets.QFrame(self.ip)
        self.line.setGeometry(QtCore.QRect(0, 160, 1091, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.clear_ip_log = QtWidgets.QPushButton(self.ip)
        self.clear_ip_log.setGeometry(QtCore.QRect(300, 180, 93, 28))
        self.clear_ip_log.setObjectName("clear_ip_log")
        self.clear_all_ip_log = QtWidgets.QPushButton(self.ip)
        self.clear_all_ip_log.setGeometry(QtCore.QRect(410, 180, 121, 28))
        self.clear_all_ip_log.setObjectName("clear_all_ip_log")
        self.ip_send = QtWidgets.QPushButton(self.ip)
        self.ip_send.setGeometry(QtCore.QRect(980, 130, 93, 28))
        self.ip_send.setObjectName("ip_send")
        self.ip_source_port = QtWidgets.QLineEdit(self.ip)
        self.ip_source_port.setGeometry(QtCore.QRect(970, 20, 111, 20))
        self.ip_source_port.setObjectName("ip_source_port")
        self.label_54 = QtWidgets.QLabel(self.ip)
        self.label_54.setGeometry(QtCore.QRect(860, 20, 101, 16))
        self.label_54.setObjectName("label_54")
        self.tabWidget.addTab(self.ip, "")
        self.tcp = QtWidgets.QWidget()
        self.tcp.setObjectName("tcp")
        self.label_14 = QtWidgets.QLabel(self.tcp)
        self.label_14.setGeometry(QtCore.QRect(10, 20, 111, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tcp)
        self.label_15.setGeometry(QtCore.QRect(330, 20, 151, 16))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.tcp)
        self.label_16.setGeometry(QtCore.QRect(670, 20, 101, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.tcp)
        self.label_17.setGeometry(QtCore.QRect(860, 20, 141, 16))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.tcp)
        self.label_18.setGeometry(QtCore.QRect(10, 60, 121, 16))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.tcp)
        self.label_19.setGeometry(QtCore.QRect(220, 60, 91, 16))
        self.label_19.setObjectName("label_19")
        self.label_21 = QtWidgets.QLabel(self.tcp)
        self.label_21.setGeometry(QtCore.QRect(10, 100, 31, 16))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.tcp)
        self.label_22.setGeometry(QtCore.QRect(80, 100, 31, 16))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.tcp)
        self.label_23.setGeometry(QtCore.QRect(140, 100, 31, 16))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.tcp)
        self.label_24.setGeometry(QtCore.QRect(200, 100, 31, 16))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.tcp)
        self.label_25.setGeometry(QtCore.QRect(260, 100, 31, 16))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.tcp)
        self.label_26.setGeometry(QtCore.QRect(320, 100, 31, 16))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.tcp)
        self.label_27.setGeometry(QtCore.QRect(390, 100, 91, 16))
        self.label_27.setObjectName("label_27")
        self.label_29 = QtWidgets.QLabel(self.tcp)
        self.label_29.setGeometry(QtCore.QRect(610, 100, 111, 16))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.tcp)
        self.label_30.setGeometry(QtCore.QRect(440, 60, 51, 20))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.tcp)
        self.label_31.setGeometry(QtCore.QRect(10, 140, 31, 16))
        self.label_31.setObjectName("label_31")
        self.tcp_send = QtWidgets.QPushButton(self.tcp)
        self.tcp_send.setGeometry(QtCore.QRect(990, 130, 93, 28))
        self.tcp_send.setObjectName("tcp_send")
        self.tcp_source_address = QtWidgets.QLineEdit(self.tcp)
        self.tcp_source_address.setGeometry(QtCore.QRect(140, 20, 171, 20))
        self.tcp_source_address.setObjectName("tcp_source_address")
        self.tcp_destination_address = QtWidgets.QLineEdit(self.tcp)
        self.tcp_destination_address.setGeometry(QtCore.QRect(490, 20, 171, 20))
        self.tcp_destination_address.setObjectName("tcp_destination_address")
        self.tcp_source_port = QtWidgets.QLineEdit(self.tcp)
        self.tcp_source_port.setGeometry(QtCore.QRect(770, 20, 81, 20))
        self.tcp_source_port.setObjectName("tcp_source_port")
        self.tcp_destination_port = QtWidgets.QLineEdit(self.tcp)
        self.tcp_destination_port.setGeometry(QtCore.QRect(1000, 20, 81, 20))
        self.tcp_destination_port.setObjectName("tcp_destination_port")
        self.tcp_sequence_number = QtWidgets.QLineEdit(self.tcp)
        self.tcp_sequence_number.setGeometry(QtCore.QRect(140, 60, 71, 20))
        self.tcp_sequence_number.setObjectName("tcp_sequence_number")
        self.tcp_ack_number = QtWidgets.QLineEdit(self.tcp)
        self.tcp_ack_number.setGeometry(QtCore.QRect(320, 60, 111, 20))
        self.tcp_ack_number.setObjectName("tcp_ack_number")
        self.tcp_urg = QtWidgets.QLineEdit(self.tcp)
        self.tcp_urg.setGeometry(QtCore.QRect(50, 100, 21, 20))
        self.tcp_urg.setObjectName("tcp_urg")
        self.tcp_ack = QtWidgets.QLineEdit(self.tcp)
        self.tcp_ack.setGeometry(QtCore.QRect(110, 100, 21, 20))
        self.tcp_ack.setObjectName("tcp_ack")
        self.tcp_psh = QtWidgets.QLineEdit(self.tcp)
        self.tcp_psh.setGeometry(QtCore.QRect(170, 100, 21, 20))
        self.tcp_psh.setObjectName("tcp_psh")
        self.tcp_rst = QtWidgets.QLineEdit(self.tcp)
        self.tcp_rst.setGeometry(QtCore.QRect(230, 100, 21, 20))
        self.tcp_rst.setObjectName("tcp_rst")
        self.tcp_syn = QtWidgets.QLineEdit(self.tcp)
        self.tcp_syn.setGeometry(QtCore.QRect(290, 100, 21, 20))
        self.tcp_syn.setObjectName("tcp_syn")
        self.tcp_fin = QtWidgets.QLineEdit(self.tcp)
        self.tcp_fin.setGeometry(QtCore.QRect(350, 100, 21, 20))
        self.tcp_fin.setObjectName("tcp_fin")
        self.tcp_window_size = QtWidgets.QLineEdit(self.tcp)
        self.tcp_window_size.setGeometry(QtCore.QRect(500, 100, 101, 20))
        self.tcp_window_size.setObjectName("tcp_window_size")
        self.tcp_urgent_pointer = QtWidgets.QLineEdit(self.tcp)
        self.tcp_urgent_pointer.setGeometry(QtCore.QRect(730, 100, 351, 20))
        self.tcp_urgent_pointer.setObjectName("tcp_urgent_pointer")
        self.tcp_option = QtWidgets.QLineEdit(self.tcp)
        self.tcp_option.setGeometry(QtCore.QRect(510, 60, 571, 20))
        self.tcp_option.setObjectName("tcp_option")
        self.tcp_data = QtWidgets.QLineEdit(self.tcp)
        self.tcp_data.setGeometry(QtCore.QRect(50, 140, 931, 20))
        self.tcp_data.setObjectName("tcp_data")
        self.tcp_log = QtWidgets.QTableWidget(self.tcp)
        self.tcp_log.setGeometry(QtCore.QRect(10, 220, 521, 231))
        self.tcp_log.setObjectName("tcp_log")
        self.tcp_log.setColumnCount(4)
        self.tcp_log.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tcp_log.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tcp_log.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tcp_log.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tcp_log.setHorizontalHeaderItem(3, item)
        self.label_20 = QtWidgets.QLabel(self.tcp)
        self.label_20.setGeometry(QtCore.QRect(10, 190, 171, 16))
        self.label_20.setObjectName("label_20")
        self.tcp_detail_list = QtWidgets.QListView(self.tcp)
        self.tcp_detail_list.setGeometry(QtCore.QRect(570, 220, 511, 231))
        self.tcp_detail_list.setObjectName("tcp_detail_list")
        self.label_40 = QtWidgets.QLabel(self.tcp)
        self.label_40.setGeometry(QtCore.QRect(560, 190, 171, 16))
        self.label_40.setObjectName("label_40")
        self.clear_tcp_log = QtWidgets.QPushButton(self.tcp)
        self.clear_tcp_log.setGeometry(QtCore.QRect(290, 180, 93, 28))
        self.clear_tcp_log.setObjectName("clear_tcp_log")
        self.clear_all_tcp_log = QtWidgets.QPushButton(self.tcp)
        self.clear_all_tcp_log.setGeometry(QtCore.QRect(400, 180, 121, 28))
        self.clear_all_tcp_log.setObjectName("clear_all_tcp_log")
        self.line_3 = QtWidgets.QFrame(self.tcp)
        self.line_3.setGeometry(QtCore.QRect(0, 160, 1091, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.tabWidget.addTab(self.tcp, "")
        self.udp = QtWidgets.QWidget()
        self.udp.setObjectName("udp")
        self.label_32 = QtWidgets.QLabel(self.udp)
        self.label_32.setGeometry(QtCore.QRect(10, 20, 141, 16))
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.udp)
        self.label_33.setGeometry(QtCore.QRect(310, 20, 161, 16))
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.udp)
        self.label_34.setGeometry(QtCore.QRect(650, 20, 101, 16))
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.udp)
        self.label_35.setGeometry(QtCore.QRect(850, 20, 141, 16))
        self.label_35.setObjectName("label_35")
        self.label_38 = QtWidgets.QLabel(self.udp)
        self.label_38.setGeometry(QtCore.QRect(10, 60, 41, 16))
        self.label_38.setObjectName("label_38")
        self.udp_send = QtWidgets.QPushButton(self.udp)
        self.udp_send.setGeometry(QtCore.QRect(990, 50, 93, 28))
        self.udp_send.setObjectName("udp_send")
        self.udp_source_address = QtWidgets.QLineEdit(self.udp)
        self.udp_source_address.setGeometry(QtCore.QRect(130, 20, 171, 20))
        self.udp_source_address.setObjectName("udp_source_address")
        self.udp_destination_address = QtWidgets.QLineEdit(self.udp)
        self.udp_destination_address.setGeometry(QtCore.QRect(470, 20, 171, 20))
        self.udp_destination_address.setObjectName("udp_destination_address")
        self.udp_source_port = QtWidgets.QLineEdit(self.udp)
        self.udp_source_port.setGeometry(QtCore.QRect(750, 20, 91, 20))
        self.udp_source_port.setObjectName("udp_source_port")
        self.udp_destination_port = QtWidgets.QLineEdit(self.udp)
        self.udp_destination_port.setGeometry(QtCore.QRect(990, 20, 91, 20))
        self.udp_destination_port.setObjectName("udp_destination_port")
        self.udp_data = QtWidgets.QLineEdit(self.udp)
        self.udp_data.setGeometry(QtCore.QRect(60, 60, 911, 20))
        self.udp_data.setObjectName("udp_data")
        self.udp_log = QtWidgets.QTableWidget(self.udp)
        self.udp_log.setGeometry(QtCore.QRect(10, 151, 521, 301))
        self.udp_log.setObjectName("udp_log")
        self.udp_log.setColumnCount(4)
        self.udp_log.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.udp_log.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.udp_log.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.udp_log.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.udp_log.setHorizontalHeaderItem(3, item)
        self.label_28 = QtWidgets.QLabel(self.udp)
        self.label_28.setGeometry(QtCore.QRect(10, 109, 161, 16))
        self.label_28.setObjectName("label_28")
        self.label_41 = QtWidgets.QLabel(self.udp)
        self.label_41.setGeometry(QtCore.QRect(570, 109, 171, 16))
        self.label_41.setObjectName("label_41")
        self.udp_detail_list = QtWidgets.QListView(self.udp)
        self.udp_detail_list.setGeometry(QtCore.QRect(570, 150, 511, 301))
        self.udp_detail_list.setObjectName("udp_detail_list")
        self.clear_udp_log = QtWidgets.QPushButton(self.udp)
        self.clear_udp_log.setGeometry(QtCore.QRect(300, 109, 93, 28))
        self.clear_udp_log.setObjectName("clear_udp_log")
        self.clear_all_udp_log = QtWidgets.QPushButton(self.udp)
        self.clear_all_udp_log.setGeometry(QtCore.QRect(410, 109, 121, 28))
        self.clear_all_udp_log.setObjectName("clear_all_udp_log")
        self.line_4 = QtWidgets.QFrame(self.udp)
        self.line_4.setGeometry(QtCore.QRect(0, 80, 1091, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.tabWidget.addTab(self.udp, "")
        self.arp = QtWidgets.QWidget()
        self.arp.setObjectName("arp")
        self.label_43 = QtWidgets.QLabel(self.arp)
        self.label_43.setGeometry(QtCore.QRect(240, 100, 121, 16))
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.arp)
        self.label_44.setGeometry(QtCore.QRect(10, 20, 151, 16))
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.arp)
        self.label_45.setGeometry(QtCore.QRect(540, 20, 201, 16))
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.arp)
        self.label_46.setGeometry(QtCore.QRect(10, 60, 151, 16))
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(self.arp)
        self.label_47.setGeometry(QtCore.QRect(540, 60, 181, 16))
        self.label_47.setObjectName("label_47")
        self.arp_send = QtWidgets.QPushButton(self.arp)
        self.arp_send.setGeometry(QtCore.QRect(980, 100, 93, 28))
        self.arp_send.setObjectName("arp_send")
        self.arp_operation_type = QtWidgets.QComboBox(self.arp)
        self.arp_operation_type.setGeometry(QtCore.QRect(380, 100, 87, 22))
        self.arp_operation_type.setObjectName("arp_operation_type")
        self.arp_operation_type.addItem("")
        self.arp_operation_type.addItem("")
        self.arp_source_mac = QtWidgets.QLineEdit(self.arp)
        self.arp_source_mac.setGeometry(QtCore.QRect(160, 20, 321, 20))
        self.arp_source_mac.setObjectName("arp_source_mac")
        self.arp_destination_mac = QtWidgets.QLineEdit(self.arp)
        self.arp_destination_mac.setGeometry(QtCore.QRect(750, 20, 321, 20))
        self.arp_destination_mac.setObjectName("arp_destination_mac")
        self.arp_source_ip = QtWidgets.QLineEdit(self.arp)
        self.arp_source_ip.setGeometry(QtCore.QRect(160, 60, 321, 20))
        self.arp_source_ip.setObjectName("arp_source_ip")
        self.arp_destination_ip = QtWidgets.QLineEdit(self.arp)
        self.arp_destination_ip.setGeometry(QtCore.QRect(750, 60, 321, 20))
        self.arp_destination_ip.setObjectName("arp_destination_ip")
        self.label_4 = QtWidgets.QLabel(self.arp)
        self.label_4.setGeometry(QtCore.QRect(10, 100, 81, 16))
        self.label_4.setObjectName("label_4")
        self.arp_interface = QtWidgets.QLineEdit(self.arp)
        self.arp_interface.setGeometry(QtCore.QRect(90, 100, 113, 20))
        self.arp_interface.setObjectName("arp_interface")
        self.arp_log = QtWidgets.QTableWidget(self.arp)
        self.arp_log.setGeometry(QtCore.QRect(10, 200, 521, 231))
        self.arp_log.setObjectName("arp_log")
        self.arp_log.setColumnCount(4)
        self.arp_log.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.arp_log.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.arp_log.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.arp_log.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.arp_log.setHorizontalHeaderItem(3, item)
        self.label_36 = QtWidgets.QLabel(self.arp)
        self.label_36.setGeometry(QtCore.QRect(10, 160, 161, 16))
        self.label_36.setObjectName("label_36")
        self.arp_detail_list = QtWidgets.QListView(self.arp)
        self.arp_detail_list.setGeometry(QtCore.QRect(580, 200, 501, 231))
        self.arp_detail_list.setObjectName("arp_detail_list")
        self.label_42 = QtWidgets.QLabel(self.arp)
        self.label_42.setGeometry(QtCore.QRect(580, 160, 171, 16))
        self.label_42.setObjectName("label_42")
        self.clear_arp_log = QtWidgets.QPushButton(self.arp)
        self.clear_arp_log.setGeometry(QtCore.QRect(300, 150, 93, 28))
        self.clear_arp_log.setObjectName("clear_arp_log")
        self.clear_all_arp_log = QtWidgets.QPushButton(self.arp)
        self.clear_all_arp_log.setGeometry(QtCore.QRect(410, 150, 121, 28))
        self.clear_all_arp_log.setObjectName("clear_all_arp_log")
        self.line_2 = QtWidgets.QFrame(self.arp)
        self.line_2.setGeometry(QtCore.QRect(0, 130, 1091, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.tabWidget.addTab(self.arp, "")
        self.icmp = QtWidgets.QWidget()
        self.icmp.setObjectName("icmp")
        self.label_48 = QtWidgets.QLabel(self.icmp)
        self.label_48.setGeometry(QtCore.QRect(10, 20, 31, 16))
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(self.icmp)
        self.label_49.setGeometry(QtCore.QRect(230, 20, 51, 16))
        self.label_49.setObjectName("label_49")
        self.label_52 = QtWidgets.QLabel(self.icmp)
        self.label_52.setGeometry(QtCore.QRect(430, 20, 131, 16))
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(self.icmp)
        self.label_53.setGeometry(QtCore.QRect(760, 20, 131, 16))
        self.label_53.setObjectName("label_53")
        self.icmp_send = QtWidgets.QPushButton(self.icmp)
        self.icmp_send.setGeometry(QtCore.QRect(990, 50, 93, 28))
        self.icmp_send.setObjectName("icmp_send")
        self.label_66 = QtWidgets.QLabel(self.icmp)
        self.label_66.setGeometry(QtCore.QRect(10, 60, 121, 16))
        self.label_66.setObjectName("label_66")
        self.label_67 = QtWidgets.QLabel(self.icmp)
        self.label_67.setGeometry(QtCore.QRect(480, 60, 161, 16))
        self.label_67.setObjectName("label_67")
        self.icmp_type = QtWidgets.QComboBox(self.icmp)
        self.icmp_type.setGeometry(QtCore.QRect(60, 20, 111, 22))
        self.icmp_type.setObjectName("icmp_type")
        self.icmp_type.addItem("")
        self.icmp_type.addItem("")
        self.icmp_type.addItem("")
        self.icmp_source_address = QtWidgets.QLineEdit(self.icmp)
        self.icmp_source_address.setGeometry(QtCore.QRect(140, 60, 321, 20))
        self.icmp_source_address.setObjectName("icmp_source_address")
        self.icmp_destination_address = QtWidgets.QLineEdit(self.icmp)
        self.icmp_destination_address.setGeometry(QtCore.QRect(650, 60, 321, 20))
        self.icmp_destination_address.setObjectName("icmp_destination_address")
        self.icmp_code = QtWidgets.QLineEdit(self.icmp)
        self.icmp_code.setGeometry(QtCore.QRect(290, 20, 121, 20))
        self.icmp_code.setObjectName("icmp_code")
        self.icmp_identification = QtWidgets.QLineEdit(self.icmp)
        self.icmp_identification.setGeometry(QtCore.QRect(550, 20, 181, 20))
        self.icmp_identification.setObjectName("icmp_identification")
        self.icmp_sequence_number = QtWidgets.QLineEdit(self.icmp)
        self.icmp_sequence_number.setGeometry(QtCore.QRect(900, 20, 181, 20))
        self.icmp_sequence_number.setObjectName("icmp_sequence_number")
        self.label_37 = QtWidgets.QLabel(self.icmp)
        self.label_37.setGeometry(QtCore.QRect(10, 120, 181, 16))
        self.label_37.setObjectName("label_37")
        self.icmp_log = QtWidgets.QTableWidget(self.icmp)
        self.icmp_log.setGeometry(QtCore.QRect(10, 160, 521, 291))
        self.icmp_log.setObjectName("icmp_log")
        self.icmp_log.setColumnCount(3)
        self.icmp_log.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.icmp_log.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.icmp_log.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.icmp_log.setHorizontalHeaderItem(2, item)
        self.icmp_detail_list = QtWidgets.QListView(self.icmp)
        self.icmp_detail_list.setGeometry(QtCore.QRect(580, 160, 501, 291))
        self.icmp_detail_list.setObjectName("icmp_detail_list")
        self.label_50 = QtWidgets.QLabel(self.icmp)
        self.label_50.setGeometry(QtCore.QRect(580, 120, 171, 16))
        self.label_50.setObjectName("label_50")
        self.clear_icmp_log = QtWidgets.QPushButton(self.icmp)
        self.clear_icmp_log.setGeometry(QtCore.QRect(290, 110, 93, 28))
        self.clear_icmp_log.setObjectName("clear_icmp_log")
        self.clear_all_icmp_log = QtWidgets.QPushButton(self.icmp)
        self.clear_all_icmp_log.setGeometry(QtCore.QRect(400, 110, 121, 28))
        self.clear_all_icmp_log.setObjectName("clear_all_icmp_log")
        self.line_5 = QtWidgets.QFrame(self.icmp)
        self.line_5.setGeometry(QtCore.QRect(0, 90, 1091, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.tabWidget.addTab(self.icmp, "")
        iSender.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(iSender)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1096, 23))
        self.menubar.setObjectName("menubar")
        iSender.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(iSender)
        self.statusbar.setObjectName("statusbar")
        iSender.setStatusBar(self.statusbar)
        self.actionip = QtWidgets.QAction(iSender)
        self.actionip.setObjectName("actionip")
        self.actiontcp = QtWidgets.QAction(iSender)
        self.actiontcp.setObjectName("actiontcp")
        self.actionudp = QtWidgets.QAction(iSender)
        self.actionudp.setObjectName("actionudp")

        self.retranslateUi(iSender)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(iSender)

    def retranslateUi(self, iSender):
        _translate = QtCore.QCoreApplication.translate
        iSender.setWindowTitle(_translate("iSender", "MainWindow"))
        item = self.log_widget.horizontalHeaderItem(0)
        item.setText(_translate("iSender", "Protocol"))
        item = self.log_widget.horizontalHeaderItem(1)
        item.setText(_translate("iSender", "Source Address"))
        item = self.log_widget.horizontalHeaderItem(2)
        item.setText(_translate("iSender", "Destination Address"))
        item = self.log_widget.horizontalHeaderItem(3)
        item.setText(_translate("iSender", "Source Port"))
        item = self.log_widget.horizontalHeaderItem(4)
        item.setText(_translate("iSender", "Destination Port"))
        self.label_51.setText(_translate("iSender", "History Message"))
        self.label_69.setText(_translate("iSender", "Detail Information"))
        self.clear_log.setText(_translate("iSender", "Clear"))
        self.clear_all_log.setText(_translate("iSender", "Clear All(0)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("iSender", "log"))
        self.label_3.setText(_translate("iSender", "Type of Service"))
        self.label_5.setText(_translate("iSender", "Identification"))
        self.label_6.setText(_translate("iSender", "DF"))
        self.label_7.setText(_translate("iSender", "MF"))
        self.label_8.setText(_translate("iSender", "Time to Live"))
        self.label_9.setText(_translate("iSender", "Protocol"))
        self.label_11.setText(_translate("iSender", "Source Address"))
        self.label_12.setText(_translate("iSender", "Destination Address"))
        self.label_13.setText(_translate("iSender", "Option"))
        self.label.setText(_translate("iSender", "Data"))
        self.label_57.setText(_translate("iSender", "Offset"))
        self.ip_protocol.setItemText(0, _translate("iSender", "TCP"))
        self.ip_protocol.setItemText(1, _translate("iSender", "UDP"))
        self.ip_protocol.setItemText(2, _translate("iSender", "ICMP"))
        self.label_2.setText(_translate("iSender", "Destination Port"))
        item = self.ip_log.horizontalHeaderItem(0)
        item.setText(_translate("iSender", "Source Address"))
        item = self.ip_log.horizontalHeaderItem(1)
        item.setText(_translate("iSender", "Destination Address"))
        item = self.ip_log.horizontalHeaderItem(2)
        item.setText(_translate("iSender", "Source Port"))
        item = self.ip_log.horizontalHeaderItem(3)
        item.setText(_translate("iSender", "Destination Port"))
        self.label_10.setText(_translate("iSender", "History IP Packet"))
        self.label_39.setText(_translate("iSender", "Detail Information"))
        self.clear_ip_log.setText(_translate("iSender", "clear"))
        self.clear_all_ip_log.setText(_translate("iSender", "Clear All(0)"))
        self.ip_send.setText(_translate("iSender", "send"))
        self.label_54.setText(_translate("iSender", "source Port"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ip), _translate("iSender", "ip"))
        self.label_14.setText(_translate("iSender", "Source Address"))
        self.label_15.setText(_translate("iSender", "Destination Address"))
        self.label_16.setText(_translate("iSender", "Source Port"))
        self.label_17.setText(_translate("iSender", "Destination Port"))
        self.label_18.setText(_translate("iSender", "Sequence Number"))
        self.label_19.setText(_translate("iSender", "ACK Number"))
        self.label_21.setText(_translate("iSender", "URG"))
        self.label_22.setText(_translate("iSender", "ACK"))
        self.label_23.setText(_translate("iSender", "PSH"))
        self.label_24.setText(_translate("iSender", "RST"))
        self.label_25.setText(_translate("iSender", "SYN"))
        self.label_26.setText(_translate("iSender", "FIN"))
        self.label_27.setText(_translate("iSender", "Window Size"))
        self.label_29.setText(_translate("iSender", "Urgent Pointer"))
        self.label_30.setText(_translate("iSender", "Option"))
        self.label_31.setText(_translate("iSender", "Data"))
        self.tcp_send.setText(_translate("iSender", "Send"))
        item = self.tcp_log.horizontalHeaderItem(0)
        item.setText(_translate("iSender", "Source Address"))
        item = self.tcp_log.horizontalHeaderItem(1)
        item.setText(_translate("iSender", "Destination Address"))
        item = self.tcp_log.horizontalHeaderItem(2)
        item.setText(_translate("iSender", "Source Port"))
        item = self.tcp_log.horizontalHeaderItem(3)
        item.setText(_translate("iSender", "Destination Port"))
        self.label_20.setText(_translate("iSender", "History TCP Packet"))
        self.label_40.setText(_translate("iSender", "Detail Information"))
        self.clear_tcp_log.setText(_translate("iSender", "clear"))
        self.clear_all_tcp_log.setText(_translate("iSender", "Clear All(0)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tcp), _translate("iSender", "tcp"))
        self.label_32.setText(_translate("iSender", "Source Address"))
        self.label_33.setText(_translate("iSender", "Destination Address"))
        self.label_34.setText(_translate("iSender", "Source Port"))
        self.label_35.setText(_translate("iSender", "Destination Port"))
        self.label_38.setText(_translate("iSender", "Data"))
        self.udp_send.setText(_translate("iSender", "Send"))
        item = self.udp_log.horizontalHeaderItem(0)
        item.setText(_translate("iSender", "Source Address"))
        item = self.udp_log.horizontalHeaderItem(1)
        item.setText(_translate("iSender", "Destination Address"))
        item = self.udp_log.horizontalHeaderItem(2)
        item.setText(_translate("iSender", "Source Port"))
        item = self.udp_log.horizontalHeaderItem(3)
        item.setText(_translate("iSender", "Destination Port"))
        self.label_28.setText(_translate("iSender", "History UDP Packet"))
        self.label_41.setText(_translate("iSender", "Detail Information"))
        self.clear_udp_log.setText(_translate("iSender", "clear"))
        self.clear_all_udp_log.setText(_translate("iSender", "Clear All(0)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.udp), _translate("iSender", "udp"))
        self.label_43.setText(_translate("iSender", "Operation Type"))
        self.label_44.setText(_translate("iSender", "Source MAC Address"))
        self.label_45.setText(_translate("iSender", "Destination MAC Address"))
        self.label_46.setText(_translate("iSender", "Source IP Address"))
        self.label_47.setText(_translate("iSender", "Destination IP Address"))
        self.arp_send.setText(_translate("iSender", "Send"))
        self.arp_operation_type.setItemText(0, _translate("iSender", "request"))
        self.arp_operation_type.setItemText(1, _translate("iSender", "reply"))
        self.label_4.setText(_translate("iSender", "interface"))
        item = self.arp_log.horizontalHeaderItem(0)
        item.setText(_translate("iSender", "Source IP"))
        item = self.arp_log.horizontalHeaderItem(1)
        item.setText(_translate("iSender", "Destination IP"))
        item = self.arp_log.horizontalHeaderItem(2)
        item.setText(_translate("iSender", "Source MAC"))
        item = self.arp_log.horizontalHeaderItem(3)
        item.setText(_translate("iSender", "Destination MAC"))
        self.label_36.setText(_translate("iSender", "History ARP Packet"))
        self.label_42.setText(_translate("iSender", "Detail Information"))
        self.clear_arp_log.setText(_translate("iSender", "clear"))
        self.clear_all_arp_log.setText(_translate("iSender", "Clear All(0)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.arp), _translate("iSender", "arp"))
        self.label_48.setText(_translate("iSender", "Type"))
        self.label_49.setText(_translate("iSender", "Code"))
        self.label_52.setText(_translate("iSender", "Identification"))
        self.label_53.setText(_translate("iSender", "Sequence Number"))
        self.icmp_send.setText(_translate("iSender", "Send"))
        self.label_66.setText(_translate("iSender", "Source Address"))
        self.label_67.setText(_translate("iSender", "Destination Address"))
        self.icmp_type.setItemText(0, _translate("iSender", "request"))
        self.icmp_type.setItemText(1, _translate("iSender", "reply"))
        self.icmp_type.setItemText(2, _translate("iSender", "time out"))
        self.label_37.setText(_translate("iSender", "History ICMP Packet"))
        item = self.icmp_log.horizontalHeaderItem(0)
        item.setText(_translate("iSender", "Source Address"))
        item = self.icmp_log.horizontalHeaderItem(1)
        item.setText(_translate("iSender", "Destination Address"))
        item = self.icmp_log.horizontalHeaderItem(2)
        item.setText(_translate("iSender", "Type"))
        self.label_50.setText(_translate("iSender", "Detail Information"))
        self.clear_icmp_log.setText(_translate("iSender", "clear"))
        self.clear_all_icmp_log.setText(_translate("iSender", "Clear All(0)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.icmp), _translate("iSender", "icmp"))
        self.actionip.setText(_translate("iSender", "ip"))
        self.actiontcp.setText(_translate("iSender", "tcp"))
        self.actionudp.setText(_translate("iSender", "udp"))

